### ISSUE TITLE
NPE Exception

### ISSUE THREAD

**Issue by k-jiang** [RegalOwl/HyperConomy#107]
> [HyperConomy] Task #192 for HyperConomy v0.975.7 generated an exception
java.lang.NullPointerException
        at regalowl.hyperconomy.display.ItemDisplay.makeDisplay(ItemDisplay.java:112) ~[?:?]
        at regalowl.hyperconomy.display.ItemDisplay.refresh(ItemDisplay.java:119) ~[?:?]
        at regalowl.hyperconomy.display.ItemDisplayHandler$2.run(ItemDisplayHandler.java:104) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-survival.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

using Spigot 1.9.4 and HyperMerchant v1.6-dev build 30 http://ci.citizensnpcs.co/job/HyperMerchant/

**Comment by RegalOwl** [comment]
This is likely related to deleting an item and an item display referencing it not being deleted properly.  Will check this out.  Sorry for the delay, been very busy.
