### ISSUE TITLE
Economy plugin

### ISSUE THREAD

**Issue by diskawrs** [RegalOwl/HyperConomy#113]
Is there any support for CraftEconomy3? All the other Eco plugins have perished in the the netherworld.

Love this plugin but I can't run CraftEconomy and EssentialsEco both at the same time. various other plugins have moved away from the four that is mentioned on the wiki page.

Thank you. 

[00:02:45 WARN]: [HyperConomy] Task #71 for HyperConomy v0.975.6 generated an exception
java.lang.NullPointerException
        at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.hasAccount(Economy_Craftconomy3.java:254) ~[?:?]
        at regalowl.hyperconomy.bukkit.BukkitEconomy.hasAccount(BukkitEconomy.java:29) ~[?:?]
        at regalowl.hyperconomy.account.HyperPlayer.checkExternalAccount(HyperPlayer.java:105) ~[?:?]
        at regalowl.hyperconomy.account.HyperPlayer.validate(HyperPlayer.java:99) ~[?:?]
        at regalowl.hyperconomy.account.HyperPlayerManager$3.run(HyperPlayerManager.java:78) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-078e2f8-9ff3d7f]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_111]

**Comment by RegalOwl** [comment]
Sorry for the slow response.  I've been very busy recently.  This is an issue in the Vault connector for Craftconomy3 and is not related to HyperConomy.  I don't have any way to directly fix this.  You should contact either Vault or Craftconomy3 to fix this.
