### ISSUE TITLE
HyperConomy error on 1.7.10 Cauldron server

### ISSUE THREAD

**Issue by NoManaSendHelp** [RegalOwl/HyperConomy#119]
I am receiving this error when I try to /shopmenu or /remotemenu in my shop. I have Citizens2 1.7.10 version, HyperConomy v0.965.0 Lite/dev and HyperMerchant v1.56-Beta

Here is the error: http://pastebin.com/KjDMicGf

`[18:50:50] [Server thread/WARN]: [HyperConomy] Task #86 for HyperConomy v0.975 generated an exception
java.lang.NullPointerException
	at regalowl.hyperconomy.shop.ServerShop.inShop(ServerShop.java:212) ~[?:?]
	at regalowl.hyperconomy.shop.ServerShop.inShop(ServerShop.java:216) ~[?:?]
	at regalowl.hyperconomy.shop.ServerShop.updatePlayerStatus(ServerShop.java:381) ~[?:?]
	at regalowl.hyperconomy.shop.HyperShopManager$2.run(HyperShopManager.java:142) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:git-Cauldron-Reloaded-1.7.10-1.1388.1.0]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:862) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]`

**Comment by Serphetes** [comment]
I'm not on the support team for this, but also ran into this issue. 

if you haven't yet, try /servershop ban all (this allowed me to at least open the shop menu).

**Comment by RegalOwl** [comment]
This should be reported on the HyperMerchant github: https://github.com/remremrem/HyperMerchant/issues
