### ISSUE TITLE
Shop interface is'n't opening

### ISSUE THREAD

**Issue by P3pp3rDG** [RegalOwl/HyperConomy#124]
First of all i want to say that is Love the plugin and it's features!
But I have a problem, it worked fine a couple of months ago but now it seems like the shop interface isn't opening. When I right-click on my Hypermerchant nothing happens. 
And when I open and close my inventory the message "Thank you for you're continued patronage shows up in the chat.
I uninstalled and installed both plugins a couple of times. I've looked in the config and installed different versions of it but it still doesn't work. 

Can someone please help me out?

**Comment by P3pp3rDG** [comment]
This is the error in the error log, I don't know if this error is responsible for not opening the interface! 

HyperConomy[2017-03-26 14:29:52.221]
SQL write failed 1 time(s). The failing SQL statement is in the following brackets: 
[INSERT INTO hyperconomy_players (SALT, X, Y, Z, WORLD, ECONOMY, NAME, BALANCE, HASH) VALUES (?,?,?,?,?,?,?,?,?)]
Parameters: [[], [0], [0], [0], [world], [default], [Bob], [0.0], []]
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: hyperconomy_players.NAME)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.execute(DB.java:825)
	at org.sqlite.core.DB.executeUpdate(DB.java:863)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99)
	at regalowl.hyperconomy.simpledatalib.sql.DatabaseConnection.write(DatabaseConnection.java:50)
	at regalowl.hyperconomy.simpledatalib.sql.SQLWrite$WriteTask.write(SQLWrite.java:120)
	at regalowl.hyperconomy.simpledatalib.sql.SQLWrite$WriteTask.run(SQLWrite.java:113)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by RegalOwl** [comment]
You should report this on the HyperMerchant github: [here](https://github.com/remremrem/HyperMerchant/issues)
