### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by harry265481** [RegalOwl/HyperConomy#140]
I get this when I try to access the shop menu

`06:29:30  [Error] nullorg.bukkit.command.CommandException: Unhandled exception executing command 'shopmenu' in plugin HyperMerchant v1.59	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]Caused by: java.lang.IllegalArgumentException: Specified enchantment cannot be applied to this itemstack	at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:440) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	at grokswell.util.EnchantIcons.getIcon(EnchantIcons.java:138) ~[?:?]	at grokswell.hypermerchant.ShopMenu.loadPage(ShopMenu.java:205) ~[?:?]	at grokswell.hypermerchant.ShopMenu.<init>(ShopMenu.java:115) ~[?:?]	at grokswell.hypermerchant.HyperMerchantPlugin.onCommand(HyperMerchantPlugin.java:135) ~[?:?]	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.10.jar:git-Spigot-c3e4052-1953f52]	... 15 more`

**Comment by Pingger** [comment]
HyperMerchant is the issue here
