### ISSUE TITLE
1.14.4

### ISSUE THREAD

**Issue by eirikh1996** [RegalOwl/HyperConomy#159]
Hello. Will this plugin be updated to 1.14.4?

When I try to load it on 1.14.4, this happens:

[14:13:07] [Server thread/WARN]: Plugin HyperConomy v0.975.7 does not specify an api-version.
[14:13:08] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.NBTTagCompound.c()
[14:13:08] [Server thread/WARN]:        at java.lang.Class.getMethod(Unknown Source)
[14:13:08] [Server thread/WARN]:        at regalowl.hyperconomy.bukkit.NBTTools.<init>(NBTTools.java:56)
[14:13:08] [Server thread/WARN]:        at regalowl.hyperconomy.bukkit.BukkitConnector.<init>(BukkitConnector.java:84)
[14:13:08] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:13:08] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[14:13:08] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[14:13:08] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[14:13:08] [Server thread/WARN]:        at java.lang.Class.newInstance(Unknown Source)
[14:13:08] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:71)
[14:13:08] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[14:13:08] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[14:13:08] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253)
[14:13:08] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350)
[14:13:08] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202)
[14:13:08] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[14:13:08] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)

However, it will still enable without any issues

**Comment by Pingger** [comment]
Sorry, but AFAIK none of the Devs has time to spend on the Project at the moment.

The issue though looks the same to the 1.13 Bug. Mojang moved and renamed an important method and we need to go find it again ...

**Comment by eirikh1996** [comment]
well, I think it the method is called getKeys now. I did that in my fork of this, trying to make it 1.14 compatible. The biggest obstackle in 1.14 compatibility is to get in all the new IDs that were implemented in 1.13

Overall, very nice plugin

**Comment by writeescape** [comment]
Type Hyperconomy 1.14 into spigotmc

**Comment by Pingger** [comment]
> Type Hyperconomy 1.14 into spigotmc

 Excuse me, what do you mean?

**Comment by writeescape** [comment]
https://www.spigotmc.org/resources/hyperconomy-1-13-2.65028/ join my discord and I can throw you a 1.14 version
