### ISSUE TITLE
Hyperconomy suddenly stopped working (nullpointerexception)

### ISSUE THREAD

**Issue by Kalessar** [RegalOwl/HyperConomy#60]
The plugin suddenly stopped working today, ie /hc commands were no longer accessible and none of the transaction signs were working.

None of the plugins on the server, nor the spigot installation have been modified in the last 24H.

In comparaison to previous server logs on restart, today a new error appeared :

```
[18:51:21] [Server thread/INFO]: [HyperConomy] Enabling HyperConomy v0.975.3
[18:51:21] [Server thread/INFO]: [HyperConomy]Using internal economy plugin.
[18:51:21] [Server thread/INFO]: [CreeperHeal] Enabling CreeperHeal v6.7.9
[18:51:21] [Server thread/INFO]: debug: false
[18:51:22] [Server thread/INFO]: Done (2.944s)! For help, type "help" or "?"
[18:51:22] [Server thread/WARN]: [HyperConomy] Task #22 for HyperConomy v0.975.3 generated an exception
java.lang.NullPointerException
	at regalowl.hyperconomy.account.HyperPlayerManager.addPlayer(HyperPlayerManager.java:249) ~[?:?]
	at regalowl.hyperconomy.account.HyperPlayerManager$2.run(HyperPlayerManager.java:66) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot_vgbin.jar:git-Spigot-9a88a38-e2c4f20]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot_vgbin.jar:git-Spigot-9a88a38-e2c4f20]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot_vgbin.jar:git-Spigot-9a88a38-e2c4f20]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_vgbin.jar:git-Spigot-9a88a38-e2c4f20]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot_vgbin.jar:git-Spigot-9a88a38-e2c4f20]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot_vgbin.jar:git-Spigot-9a88a38-e2c4f20]
	at java.lang.Thread.run(Thread.java:724) [?:1.7.0_25]
```

**Comment by RegalOwl** [comment]
I'm not really sure what caused this but it may be fixed in the latest dev build.  Let me know if it's still a problem.
