### ISSUE TITLE
Error occurred while disabling HyperConomy v0.975.3

### ISSUE THREAD

**Issue by FlyingPikachu** [RegalOwl/HyperConomy#62]
Not a big deal, doesn't appear to affect anything. Thanks for the great plugin!

[23:33:36] [Server thread/INFO]: [HyperConomy] Disabling HyperConomy v0.975.3
[23:33:36] [Server thread/ERROR]: Error occurred while disabling HyperConomy v0.975.3 (Is it up to date?)
java.lang.NullPointerException
	at org.melonbrew.fe.VaultHandler.hasAccount(VaultHandler.java:210) ~[?:?]
	at regalowl.hyperconomy.bukkit.BukkitEconomy.hasAccount(BukkitEconomy.java:27) ~[?:?]
	at regalowl.hyperconomy.account.HyperPlayerManager.playerAccountExists(HyperPlayerManager.java:136) ~[?:?]
	at regalowl.hyperconomy.account.HyperPlayerManager.getAccount(HyperPlayerManager.java:167) ~[?:?]
	at regalowl.hyperconomy.shop.ServerShop.getOwner(ServerShop.java:374) ~[?:?]
	at regalowl.hyperconomy.shop.HyperShopManager.getShops(HyperShopManager.java:170) ~[?:?]
	at regalowl.hyperconomy.account.HyperPlayer.safeToDelete(HyperPlayer.java:189) ~[?:?]
	at regalowl.hyperconomy.account.HyperPlayerManager.purgeDeadAccounts(HyperPlayerManager.java:276) ~[?:?]
	at regalowl.hyperconomy.DataManager.shutDown(DataManager.java:234) ~[?:?]
	at regalowl.hyperconomy.HyperConomy.disable(HyperConomy.java:204) ~[?:?]
	at regalowl.hyperconomy.bukkit.BukkitConnector.onDisable(BukkitConnector.java:102) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:335) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:430) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:561) [craftbukkit.jar:git-Spigot-952179b-e87122e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by RegalOwl** [comment]
Technically this is an error in your economy plugin, not HyperConomy.  It's possible that I fixed it in the latest dev build as well, however.

**Comment by FlyingPikachu** [comment]
Okay, I'm not going to worry about it then. If the issue persists I'll nag the authors of Fé. Thanks!
