### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by FlyingPikachu** [RegalOwl/HyperConomy#71]
From v0.975.5 off of spigotmc.org

[14:34:54 WARN]: java.lang.reflect.InvocationTargetException
[14:34:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:34:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:34:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:34:54 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:34:54 WARN]:        at regalowl.hyperconomy.simpledatalib.event.EventPublisher.fireEvent(EventPublisher.java:37)
[14:34:54 WARN]:        at regalowl.hyperconomy.event.HyperEventHandler.fireEvent(HyperEventHandler.java:39)
[14:34:54 WARN]:        at regalowl.hyperconomy.bukkit.BukkitListener.onPlayerItemHeldEvent(BukkitListener.java:103)
[14:34:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:34:54 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:34:54 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:34:54 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[14:34:54 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301)
[14:34:54 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:34:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[14:34:54 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[14:34:54 WARN]:        at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:884)
[14:34:54 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInHeldItemSlot.a(SourceFile:30)
[14:34:54 WARN]:        at net.minecraft.server.v1_8_R1.PacketPlayInHeldItemSlot.a(SourceFile:8)
[14:34:54 WARN]:        at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[14:34:54 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[14:34:54 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[14:34:54 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[14:34:54 WARN]:        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[14:34:54 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[14:34:54 WARN]:        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[14:34:54 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:34:54 WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/Set;I)Lorg/bukkit/block/Block;
[14:34:54 WARN]:        at regalowl.hyperconomy.bukkit.BukkitConnector.getTargetLocation(BukkitConnector.java:288)
[14:34:54 WARN]:        at regalowl.hyperconomy.account.HyperPlayer.getTargetLocation(HyperPlayer.java:477)
[14:34:54 WARN]:        at regalowl.hyperconomy.display.TransactionSignHandler.onScrollingStockChange(TransactionSignHandler.java:39)
[14:34:54 WARN]:        ... 26 more

**Comment by RegalOwl** [comment]
Are you on the latest Spigot?  I had this error for a while but it went away when I upgraded.  It may have come back though, I can test it later.

**Comment by FlyingPikachu** [comment]
This server is running CraftBukkit version git-Spigot-952179b-e87122e (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
[22:26:36 INFO]: You are 47 version(s) behind

Will try updating! ;)

**Comment by FlyingPikachu** [comment]
That fixed it! Thanks!
