### ISSUE TITLE
Audit error 

### ISSUE THREAD

**Issue by antoine7** [RegalOwl/HyperConomy#80]
When I use audit I have an error message
I use Bukkit 1.8.3 and v0.975.6 with craftconomy
I use mysql

[09:09:52] [Server thread/INFO]: sinel issued server command: /audit sinelael
[09:09:52] [Thread-55/WARN]: Exception in thread "Thread-55" 
[09:09:52] [Thread-55/WARN]: java.lang.NullPointerException
[09:09:52] [Thread-55/WARN]:    at regalowl.hyperconomy.command.Audit.getHyperLogTotal(Audit.java:94)
[09:09:52] [Thread-55/WARN]:    at regalowl.hyperconomy.command.Audit.access$300(Audit.java:10)
[09:09:52] [Thread-55/WARN]:    at regalowl.hyperconomy.command.Audit$1.run(Audit.java:47)
[09:09:52] [Thread-55/WARN]:    at java.lang.Thread.run(Unknown Source)
[09:09:54] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2111ms behind, skipping 42 tick(s)
[09:10:08] [Server thread/INFO]: sinel issued server command: /audit hyperconomy
[09:10:08] [Thread-56/WARN]: Exception in thread "Thread-56" 
[09:10:08] [Thread-56/WARN]: java.lang.NullPointerException
[09:10:08] [Thread-56/WARN]:    at regalowl.hyperconomy.command.Audit.getHyperLogTotal(Audit.java:94)
[09:10:08] [Thread-56/WARN]:    at regalowl.hyperconomy.command.Audit.access$300(Audit.java:10)
[09:10:08] [Thread-56/WARN]:    at regalowl.hyperconomy.command.Audit$1.run(Audit.java:47)
[09:10:08] [Thread-56/WARN]:    at java.lang.Thread.run(Unknown Source)

**Comment by RegalOwl** [comment]
The audit log was too large, or database too slow.  Not much can be done about this except clearing the log.
