### ISSUE TITLE
Error when a shop is created

### ISSUE THREAD

**Issue by Starsonlyone** [RegalOwl/HyperConomy#86]
/ss p1 name

That is what I typed and Errors  just spam my consol. The only thing that stops it is if i remove the shop completly

This is the error 

java.lang.ArrayIndexOutOfBoundsException: 0
	at regalowl.hyperconomy.command.Sell.onCommand(Sell.java:26)
	at regalowl.hyperconomy.bukkit.BukkitConnector.onCommand(BukkitConnector.java:113)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:395)
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:380)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Starsonlyone** [comment]
v0.975.0 [Dev] is the version I am running

**Comment by RegalOwl** [comment]
What version of craftbukkit are you using?  The latest builds of HyperConomy may no longer work with 1.7 builds.

**Comment by Starsonlyone** [comment]
were using cauldron version 1.7.10

**Comment by Starsonlyone** [comment]
Not sure how to change the label to waiting on you

**Comment by RegalOwl** [comment]
I would suggest reverting to build v0.974.57.  v0.975.0 was for 1.8, but Bukkit didn't allow me to tag it that way at the time.  v0.974.57 was a pretty solid build, if I remember correctly.  Hopefully this fixes your bug.  If you have data in your current HyperConomy it may be a tricky to revert.  If this is the case let me know and I can look into it further.  A fresh install will be best.
