### ISSUE TITLE
Cannot open HyperConomy shop interface with potion

### ISSUE THREAD

**Issue by Nayrisian** [RegalOwl/HyperConomy#99]
Could not pass event NPCRightClickEvent to Citizens v2.0.17-SNAPSHOT (build 1318)
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:386) [citizens-2.0.17-SNAPSHOT.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1532) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:68) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.minecraft.server.v1_9_R1.PacketPlayInUseEntity.a(SourceFile:12) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]

Caused by: java.lang.IllegalArgumentException: Potion Type is not upgradable
at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.potion.PotionData.<init>(PotionData.java:23) ~[minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.craftbukkit.v1_9_R1.potion.CraftPotionUtil.toBukkit(CraftPotionUtil.java:85) ~[minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaPotion.getBasePotionData(CraftMetaPotion.java:159) ~[minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
at regalowl.hyperconomy.bukkit.BukkitCommon.getSerializableItemStack(BukkitCommon.java:441) ~[?:?]
at regalowl.hyperconomy.bukkit.BukkitCommon.getInventory(BukkitCommon.java:265) ~[?:?]
at regalowl.hyperconomy.bukkit.BukkitConnector.getInventory(BukkitConnector.java:358) ~[?:?]
at regalowl.hyperconomy.account.HyperPlayer.getInventory(HyperPlayer.java:274) ~[?:?]
at regalowl.hyperconomy.tradeobject.ComponentTradeItem.getSellPrice(ComponentTradeItem.java:44) ~[?:?]
at regalowl.hyperconomy.tradeobject.BasicTradeObject.getSellPriceWithTax(BasicTradeObject.java:598) ~[?:?]
at grokswell.hypermerchant.ShopMenu.loadPage(ShopMenu.java:200) ~[?:?]
at grokswell.hypermerchant.ShopMenu.<init>(ShopMenu.java:116) ~[?:?]
at grokswell.hypermerchant.HyperMerchantTrait.onRightClick(HyperMerchantTrait.java:367) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-90839e6-8e5eab2]
... 24 more

This currently happens with potions of: Invisibility, Fire Resistance, Slowness, Water Breathing, Weakness, Luck, Awkward, Uncraftable, Water Bottle, Mundane and Thick potions.
There may be more but these are the ones I've checked.

Also using hypermerchant-1.6-dev, with citizens-2.0.17-SNAPSHOT as displayed in the stack trace.

**Comment by remremrem** [comment]
This looks to me like a HyperMerchant issue, and I will take a closer look this evening

**Comment by RegalOwl** [comment]
This may also just be an outdated Spigot.  Try updating to the latest Spigot to see if this is resolved.  I reported a very similar issue to the Spigot team which was resolved a day or two ago.

**Comment by remremrem** [comment]
RegalOwl is right. This doesn't seem to be an issue for me with latest spigot.

**Comment by Nayrisian** [comment]
Sorry for the late response, this was indeed an issue with the version of Spigot. This is all fixed in the "at the moment" latest version of Spigot.
